"""empty message

Revision ID: 2729250b05b1
Revises: 
Create Date: 2019-06-02 11:50:06.563695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2729250b05b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parceiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('Workshop', 'Palestra', 'Curso', name='tipo_evento'), nullable=True),
    sa.Column('id_parceiro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_parceiro'], ['parceiro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento')
    op.drop_table('parceiro')
    # ### end Alembic commands ###
