"""empty message

Revision ID: 5a0dcb612fca
Revises: 0840f3d67858
Create Date: 2019-06-04 10:26:12.313883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0dcb612fca'
down_revision = '0840f3d67858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evento', sa.Column('data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'data')
    # ### end Alembic commands ###
