"""empty message

Revision ID: 70750a215ace
Revises: 0e57dfe62bff
Create Date: 2019-06-19 00:52:52.660676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70750a215ace'
down_revision = '0e57dfe62bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parceiro', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parceiro', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parceiro', type_='foreignkey')
    op.drop_column('parceiro', 'id_usuario')
    # ### end Alembic commands ###
