"""empty message

Revision ID: c30265f78285
Revises: 2729250b05b1
Create Date: 2019-06-02 13:20:43.910377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = 'c30265f78285'
down_revision = '2729250b05b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    area_evento_enum = postgresql.ENUM('Informática', 'Medicina', 'Química', 'Administração', name='area_evento')
    area_evento_enum.create(op.get_bind())

    op.add_column('evento', sa.Column('area', sa.Enum('Informática', 'Medicina', 'Química', 'Administração', name='area_evento'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evento', 'area')
    # ### end Alembic commands ###
    area_evento_enum = postgresql.ENUM('Informática', 'Medicina', 'Química', 'Administração', name='area_evento')
    area_evento_enum.drop(op.get_bind())
