"""empty message

Revision ID: ddca1c272cc3
Revises: 5a0dcb612fca
Create Date: 2019-06-04 15:45:11.121563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddca1c272cc3'
down_revision = '5a0dcb612fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('codigo_estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_estado'], ['estado.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cidade')
    op.drop_table('estado')
    # ### end Alembic commands ###
